services:
  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    env_file:
      - ./backend/fastapi/app/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIA_PASSWORD}
      MARIADB_DATABASE: finball
    volumes:
      - ./backend/mariadb/data:/var/lib/mysql
    ports:
      - "${MARIA_PORT}:3306"

  reactnative:
    build:
      context: ./frontend/react-native
      dockerfile: Dockerfile
      args:
        FRONTEND_METRO_PORT: ${FRONTEND_METRO_PORT}
        FRONTEND_EXPO_PORT: ${FRONTEND_EXPO_PORT}
    env_file:
      - ./frontend/react-native/app/.env
    ports:
      - "${FRONTEND_METRO_PORT}:${FRONTEND_METRO_PORT}"
      - "${FRONTEND_EXPO_PORT}:${FRONTEND_EXPO_PORT}"
    entrypoint: ["/bin/sh", "-c", "npx expo start --web"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"

## 모니터링 툴
  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - "-nginx.scrape-uri=http://nginx:80/nginx_status"
    depends_on:
      - nginx
    ports:
      - "9113:9113"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"



volumes:
  grafana-storage: #grafana 컨테이너 안에서 만든 설정, 대시보드, 유저 정보 등을 EC2 호스트에 “보존”하기 위한 저장 공간